- name: Update package cache and fix broken dependencies
  become: yes
  ansible.builtin.shell: |
    apt update -y
    apt --fix-broken install -y
    apt upgrade -y

- name: Ensure systemd-resolved config directory exists
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: Disable swap
  shell: |
    swapoff -a
    (crontab -l 2>/dev/null; echo "@reboot /sbin/swapoff -a") | crontab -
  args:
    executable: /bin/bash

- name: Load required kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Apply kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Set sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1

- name: Apply sysctl settings
  command: sysctl --system

- name: Add Kubernetes GPG key
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version_short }}/deb/Release.key | \
      gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version_short }}/deb/ /


- import_tasks: install_crio.yml
- import_tasks: install_kubernetes.yml
